### ISSUE TITLE
Akka Error Running Fat Jar

### ISSUE THREAD

**Issue by stevencox** [oaqa/suim#1]
Hi, I get this error after an mvn clean package. I've added the shade plugin as suggested in several [places](https://www.assembla.com/spaces/akka/tickets/2634-akka-remote-prevents-application-from--shading--%28standalone-jar-creation%29-due-to-config-issues-in---?comment=183467573#/activity/ticket:) to solve this problem with no luck.

Perhaps I've got bad versions (Scala @ 2.10.1 and 2.11.1) of something?

Can you suggest why I might be seeing this?

```
$ java -cp ./suim-examples/target/suim-examples-0.0.1-SNAPSHOT-jar-with-dependencies.jar edu.cmu.lti.suim.examples.App local[2]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.remote.log-received-messages'
    at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:126)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:146)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:119)
    at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:157)
    at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:167)
    at akka.remote.RemoteSettings.<init>(RemoteSettings.scala:18)
    at akka.remote.RemoteActorRefProvider.<init>(RemoteActorRefProvider.scala:32)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3$$anonfun$apply$1.apply(DynamicAccess.scala:108)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3$$anonfun$apply$1.apply(DynamicAccess.scala:105)
    at akka.actor.DynamicAccess$class.withErrorHandling(DynamicAccess.scala:72)
    at akka.actor.ReflectiveDynamicAccess.withErrorHandling(DynamicAccess.scala:90)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:105)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:102)
    at scala.Either.fold(Either.scala:96)
    at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:102)
    at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:549)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:111)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:104)
    at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:64)
    at org.apache.spark.SparkEnv$.createFromSystemProperties(SparkEnv.scala:128)
    at org.apache.spark.SparkContext.<init>(SparkContext.scala:105)
    at edu.cmu.lti.suim.examples.App$.main(App.scala:37)
    at edu.cmu.lti.suim.examples.App.main(App.scala)
```

Thanks

**Comment by elmer-garduno** [comment]
Most likely is the Scala version as this example is configured to run with 2.9.3.
